-- AlterTable
ALTER TABLE "User" ADD COLUMN     "isOtpValid" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "isVerified" DROP NOT NULL,
ALTER COLUMN "otp" DROP NOT NULL,
ALTER COLUMN "otp" SET DEFAULT '000000';
