export const designation = [
  { id: 1, value: "SDE I" },
  { id: 2, value: "SDE II" },
  { id: 3, value: "Sr. SDE" },
  { id: 4, value: "Lead SDE" },
  { id: 5, value: "Architect" },
  { id: 6, value: "PM" },
  { id: 7, value: "QA" },
  { id: 8, value: "DevOps" },
  { id: 9, value: "UX Designer" },
  { id: 10, value: "UI Designer" },
  { id: 11, value: "Full-Stack Dev" },
  { id: 12, value: "Frontend Dev" },
  { id: 13, value: "Backend Dev" },
  { id: 14, value: "Data Scientist" },
  { id: 15, value: "Data Analyst" },
  { id: 16, value: "Sys Admin" },
  { id: 17, value: "Network Eng." },
  { id: 18, value: "Sec. Engineer" },
  { id: 19, value: "Tech Writer" },
  { id: 20, value: "Product Owner" },
  { id: 21, value: "Scrum Master" },
  { id: 22, value: "Intern" },
  { id: 23, value: "Undergraduate" },
  { id: 24, value: "Graduate" },
  { id: 25, value: "Research Asst." },
  { id: 26, value: "Teaching Asst." },
  { id: 27, value: "Volunteer" },
  { id: 28, value: "Co-op Student" },
  { id: 29, value: "Exchange Student" },
  { id: 30, value: "Fellow" },
  { id: 31, value: "Student" },
];
